baseURL = 'https://blog.sumitgouthaman.com/'
languageCode = 'en-us'
title = 'Sumit Gouthaman'
theme = 'ananke'

SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sumitgouthaman/"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/sumitgouthaman"