baseURL = 'https://sumitgouthaman.com/'
languageCode = 'en-us'
title = 'Sumit Gouthaman'
theme = 'ananke'

SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sumitgouthaman/"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/sumitgouthaman"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[services]
  [services.googleAnalytics]
    id = 'G-ED6QK3F0MY'